### ISSUE TITLE
Install script permission denied

### ISSUE THREAD

**Issue by fhscholl** [mbierman/Firewalla-NextDNS-CLI-install#1]
I have a Firewalla Gold running 1.9750. When I try your install script I get the following errors:

> bash: line 36: /data/nextdnstest.sh: Permission denied
> chmod: cannot access '/data/nextdnstest.sh': No such file or directory
> bash: line 46: /data/nextdnsdata.txt: Permission denied
> ✅  test saved.
> chmod: cannot access '/data/nextdnsdata.txt': No such file or directory
> ✅  data saved.
> Your nextdns ID is not set.
> Edit using your favorite editor (vi is already installed on Firewalla) run /home/pi/.firewalla/config/post_main.d/install_nextdnscli.sh and run.

The file referenced `/home/pi/.firewalla/config/post_main.d/install_nextdnscli.sh` doesn't exist

**Comment by mbierman** [comment]
Hi, I think I have fixed the issue and I updated the instructions slightly. Please give it a try and see if there are any issues now and if it is clear. 

Sorry for any trouble.

**Comment by fhscholl** [comment]
This seemed to work better, but I still had some issues. I got it working with some manual intervention. Some feedback/notes:
- The permission error when writing the files to /data still happens.
- When you open vi with a web link like that, it needs to be given the full path to save. The issue, in this case, is the location `/home/pi/.firewalla/config/post_main.d` wasn't writable by the `pi` user, so vi had to be opened with `sudo`.
- I will probably be in the minority here and I wouldn't expect a simple helper script to handle this, but I had to reconfigure nextdns after the fact because my network is larger than the default /24.

Thanks for the help!

**Comment by mbierman** [comment]
Thanks for the feedback. 

> The permission error when writing the files to /data still happens.

Can you share output? I can't replicate this issue. 

> When you open vi with a web link like that, it needs to be given the full path to save. The issue, in this case, is the location /home/pi/.firewalla/config/post_main.d wasn't writable by the pi user, so vi had to be opened with sudo.

Since it is created by pi, it should be writable. I'll add a permissions change anyway. 

> I will probably be in the minority here and I wouldn't expect a simple helper script to handle this, but I had to reconfigure nextdns after the fact because my network is larger than the default /24.

I'll mention that in the readme.
